### ISSUE TITLE
Generation of polynomial coefficients in Sharmir's secret sharing

### ISSUE THREAD

**Issue by onvej-sl** [bitaps-com/pybtc#23]
# Summary
I found a vulnerability in the implementation of Shamir's secret sharing scheme. The vulnerability allows an attacker to recover the mnemonic if the attacker knows `t'` out of `t` needed shares provided
  1. `t - t'` is low and
  2. `t` is high.

For example, the entropy of the secret is reduced by half if `t' = 15` and `t = 16`. The vulnerability is due to the way the random numbers are generated.

# Introduction
## Shamir secret sharing
Shamir secret sharing scheme allows you to split a secret into `n` shares such that every `t` shares can be used to reconstruct the secret. The scheme makes use of Lagrange interpolation theorem that says that given `t` points in the plane (such that no two points has the same x coordinate) there exists exactly one polynomial that goes through the points. The secret is represented by the constant term of a degree `t - 1` polynomial and the shares are represented by the points in the plane. Any `t` points are enough to reconstruct the polynomial and thus the secret. 

## Polynomial generation
Let me summarize how the shares are generated in your implementation. Suppose we have a one-byte secret `s` that we want to split into `n` shares such that each `t` (but no `t-1`) shares is enough to reconstruct the secret. The process is the following:
  1. Let `p` be a polynomial of degree `t - 1` over GF(256) such that
    1.1. its constant coefficient is `s` and
    1.2. the remaining `t - 1` coefficients are generated uniformly at random from GF(256).
  2. Let `x_1, ..., x_n` be a list of pairwise distinct non-zero elements from GF(256).
  3. For each `i` in `1, ..., n` let `y_i` be `p(x_i)` (evaluated in GF(256)).
  4. The shares are `(x_1, y_1), ..., (x_n, y_n)`.
 
When the secret has multiple bytes, the polynomial is generated independently for each byte, but `x_1, ..., x_n` are the same for each polynomial.

# Vulnerability
## Coefficients generation
The vulnerability lies in the fact that the coefficients aren't generated uniformly at random from GF(256). [This](https://github.com/bitaps-com/pybtc/blob/master/pybtc/functions/shamir.py#L114-L117) is how a coefficient `c` is generated:
```
    a = random.SystemRandom().randint(0, 255)
    i = int((time.time() % 0.0001) * 1000000) + 1
    c = (a * i) % 255
```
In the language of mathematics:
  1. `a` is drawn uniformly at random from `0, ..., 255`.
  2. `i` is drawn from `1, ..., 100`. Although it is not drawn uniformly at random, for the sake of simplicity let's suppose it is.
  3. The coefficient is `a * i % 255`.

The procedure suffers from the following two vulnerabilities:
  1. The coefficient is never 255.
  2. The result of `(a * i) % 255` is not uniformly distributed over `1, ..., 254`.

## First vulnerability
Since the coefficient is the remainder of `a * i` after division by 255, the coefficient is never 255. That means the coefficient is not generated uniformly.

Let's turn this vulnerability into an attack. Assume an attacker knows `t - 1` shares out of `t` shares needed to reconstruct a one-byte secret. The attacker guesses the remaining share and reconstructs the polynomial. If the guess is correct, no polynomial coefficient except for the constant one is equal to 255. In other words, if the polynomial has a coefficient except for the constant one that is equal to 255, the guess is incorrect. The probability that no coefficient is equal to 255 provided the guess is incorrect is `(255 / 256) ^ (t - 1)`. That means the attacker is able eliminate at average `256 * (255 / 256) ^ (t - 1)` out of 256 possible guesses. In other words, the entropy of the one-byte secret is lowered by `(t - 1) * log2(256 / 255)` bits.

Since the individual bytes of a multiple-byte secret are shared separately, the entropy of a `l`-bit secret is lowered by `l / 8 * (t - 1) * log2(256 / 255)` bits. Even if there where as much as 256 shares, the entropy of a 128-bit secret would be reduced to 105 bits, which is not so bad.

## Second vulnerability
Multiplication modulo a non-prime number is a tricky operation, since the function that maps `x` to `x * y  % m` is a permutation of the set `{1, ..., m - 1}` if and only if `y` is relative prime to `m`. Consequently, even if both `x` and `y` are generated uniformly at random from the set `{1, ..., m - 1}`, the result of the operation `x * y % m` isn't uniformly distributed over `{1, ..., m - 1}` unless `m` is a prime. 

Suppose for example that `m = 6` and `x`, `y` are distributed uniformly on the set `{1, ..., 6}`. This is the multiplication table `x, y -> x * y % 6`:

| y/x | 1 | 2 | 3 | 4 | 5 |
|-----|---|---|---|---|---|
| 1   | 1 | 2 | 3 | 4 | 5 |
| 2   | 2 | 4 | 0 | 2 | 4 |
| 3   | 3 | 0 | 3 | 0 | 3 |
| 4   | 4 | 2 | 4 | 2 | 4 |
| 5   | 5 | 4 | 3 | 2 | 1 |

The probability distribution of the result is:

| x * y % m   | 0    | 1    | 2    | 3    | 4    | 5    |
|-------------|------|------|------|------|------|------|
| probability | 0.16 | 0.08 | 0.24 | 0.20 | 0.24 | 0.08 |

Not only is the result not uniformly distributed, it's not even distributed over `{1, ..., m -1}`!

It can be calculated that the entropy of a coefficient generated by your implementation is about 7.72 bits. Although it seems to be sufficient, the conditional entropy of a secret provided the attacker knows `t - 1` out of `t` needed shares decreases as `t` increases.

First, suppose the secret has a single byte. The attacker guesses the remaining share and reconstructs the polynomial. If the guess is correct, each coefficient of the polynomial but the constant one follows the distribution with the entropy of 7.72 bits. If the guess is not correct, the coefficients are distributed approximately uniformly. Based on this fact, the attacker is able to calculate for each guess the probability that the guess is correct. These probabilities define a probability distribution of the secret. The key question is: What is the entropy of the distribution?

I wrote a [program](https://gist.github.com/onvej-sl/012230bb564c11bf67de009605df5f5a) that approximates the entropy using [Monte Carlo simulation](https://en.wikipedia.org/wiki/Monte_Carlo_method). The following graph shows the dependency between `t` and the entropy of a single byte secret conditioned on the knowledge of `t - 1` out of `t` needed shares:
![image](https://user-images.githubusercontent.com/38104856/124750885-4b4cae80-df26-11eb-9ca2-1c08813614da.png)
Note that the graph is jagged, this is because the simulation approximates (rather than calculates) the entropy.

Without proof, this is an upper bound for the entropy of a single byte secret conditioned on the kowledge of `t'` out of `t` needed shares:
<img src="https://latex.codecogs.com/gif.latex?H&space;<&space;log_2\left(1&space;&plus;&space;(2^{8(t&space;-&space;t')}&space;-&space;1)2^{0.14(1-t)}\right)" title="H < log2\left(1 + (2^{8(t - t')} - 1)2^{0.14(1-t)}\right)" />

Now, suppose the secret has multiple bytes. Since the individual bytes of the secret are independent, the entropy of the whole secret is the sum of the entropies of the individual bytes. This is a bit more complicated from the attacker's perspective. The attacker is able to compute a probability distribution for every single byte of the secret. The complexity of such the computation is linear in the length of the secret. Since the individual bytes of the secret are independent, the probability of a secret is the product of the probabilities of the individual bytes. The attacker now tries to guess the secret starting from the most probable one. This is the trickiest part, since the attacker cannot enumerate all the secrets. The smaller the entropy of the secret, the sooner the attack succeeds.

**Comment by onvej-sl** [comment]
> Good job, report is accepted as significant implementation bug. You will be paid 0.2 BTC as reward. Please specify your Bitcoin address.

That's kind of you. I sent you GPG signed e-mail with the address. This is the fingerprint of my public key: `3266 AF27 2D90 E4D2 A1B0 E000 C520 534E E2B9 CD3F`

> Are you going to visit ZeroNights conference on 25 august?

Nope.

**Comment by onvej-sl** [comment]
I received the reward, thanks!

**Comment by 4tochka** [comment]
Bug fixed:

https://github.com/bitaps-com/pybtc/blob/master/pybtc/functions/shamir.py#L114
https://github.com/bitaps-com/pybtc/blob/master/pybtc/functions/entropy.py#L5

NIST Randomnes tests on the fly added:
https://github.com/bitaps-com/pybtc/blob/master/pybtc/functions/entropy.py#L111

**Comment by chris7ph** [comment]
Hi bitaps team,

I've been working through your 1 tBTC ZeroNights mnemonic challenge at tbtc.bitaps.com/mnemonic/challenge and wanted to reach out directly.

I've done a fairly thorough cryptographic analysis:
- Decoded both published shares (x=3 and x=15) and confirmed their entropy values
- Investigated the Issue #23 coefficient bias in pybtc — ran full frequency analysis and confirmed the live challenge used a proper CSPRNG (flat 1.00x bias ratio), so that attack path is closed
- Verified there's no degree-reduction vulnerability exploitable with only 2 of 3 shares

The challenge is working exactly as intended — it's information-theoretically secure with 2 shares.

My question: Is the challenge still active? Is there any intention to ever release a third share, or is there a different intended solution path I'm missing?

I'm not asking for the answer handed to me — genuinely curious if there's a puzzle element I've overlooked, or if the challenge is purely a demonstration that proper SSS is unbreakable.

Thanks for building it — it's been a great deep-dive into GF(256) arithmetic.

Christopher Reid

**Comment by RAVVAN9** [comment]
I this this is the flaw ****
The core premise of Shamir’s Secret Sharing Scheme (SSSS) is that possessing t-1 shares must yield **exactly zero information** about the underlying secret.
This implementation breaks that absolute mathematical guarantee. By failing to isolate the polynomial generation process for consecutive bytes of a long secret (e.g., a BIP-39 seed), the implementation establishes **inter-byte mathematical correlation**. This architecture allows an attacker with fewer than the required threshold of shares to bypass independent byte guessing, converting an unsearchable 2^{128} space into a highly optimized tree-search or matrix-reduction problem.

## 2. Technical Anatomy of the Flaw
When dealing with multi-byte secrets (like a 16-byte/128-bit mnemonic entropy pool), pybtc handles splitting by assigning a separate polynomial to each individual byte index k:
For the scheme to maintain its security proof, every coefficient a_{k,n} across every independent byte instance k **must be sampled as an independent and identically distributed (i.i.d.) random variable.**
However, split_secret introduces a persistent state across the byte iteration boundary:
```python
e = generate_entropy(hex=False)
e_i = 0
for b in secret:
    q = [b]

    for i in range(threshold - 1):
        if e_i < len(e):
            a = e[e_i]
            e_i += 1
        else:
            e = generate_entropy(hex=False)
            a = e[0]
            e_i = 1
        q.append(a)

```
### The Mechanism of Failure
 1. **The Sliding Index Pointer (e_i):** The pointer e_i is never reset or completely decoupled between iterations of the outer for b in secret: loop. It continues moving linearly through the byte-string array returned by generate_entropy.
 2. **Sequential Dependency Chaining:** Because of this continuous consumption pattern, the trailing coefficients of the polynomial for secret byte s_k are pulled from the exact same memory layout slice adjacent to the leading coefficients of secret byte s_{k+1}.
 3. **Static Evaluation Coordinates:** Across this entire continuous state consumption, the physical evaluation points—the x-coordinates (shares_indexes)—remain totally static.
## 3. Exploitability & Real-World Impact
This design degrades the security properties of the algorithm down to a **sliding-window stream cipher with a leaky internal state.**
### Exploiting the 1 BTC Challenge Configuration
The live challenge operates under a t=3 threshold configuration, and explicitly provides exactly t-1 shares (Share 1 at x=3, and Share 2 at x=15).
Because an attacker holds 2 valid shares, they can instantly solve the system of linear equations for any byte s_k down to a single remaining unknown value: the highest-degree coefficient a_{k,2}.
```
Byte 0:  [s_0] ---> Coefficient [a_0,1] ---> Coefficient [a_0,2] 
                                                            |
                                               (Chained State/Entropy Pointer)
                                                            v
Byte 1:  [s_1] ---> Coefficient [a_1,1] ---> Coefficient [a_1,2]

```
In a secure implementation, a_{0,2} and a_{1,1} are perfectly independent; knowing one does not narrow down the other.
In this implementation, because a_{0,2} and a_{1,1} are extracted sequentially from the same entropy chunk e, **the choice of valid coefficients for the next byte is tightly constrained by the physical output state of the previous byte's evaluation.**
### The Depth-First Attack Vector
An attacker does not need to brute-force a 2^{128} space. Instead, they can construct a tree-search algorithm:
 1. Make a candidate guess for the first secret byte s_0.
 2. Compute the exact unique polynomial coefficients (a_{0,1} and a_{0,2}) required to produce the matching values found in the x=3 and x=15 shares.
 3. Use the known progression layout of the entropy pointer to severely isolate or validate the valid candidate space for the coefficients of byte s_1.
 4. Discard any branch immediately if the linear relationship between the derived coefficients fails the entropy continuity test, or if the resulting byte sequence violates the terminal 4-bit BIP-39 mnemonic checksum.
By eliminating candidate branches at the byte-by-byte boundary rather than searching the entire key space globally, the complexity of the threshold bypass drops into a range trivial for modern computing environments.
## 4. Engineering Remediation
To safely decouple the internal execution loop, the application must enforce strict cryptographic isolation per byte slice. This is achieved by resetting the generation pool, utilizing an inline cryptographically secure pseudo-random number generator (CSPRNG), and leveraging pre-allocated, mutable memory structures to eliminate timing and allocation side-channels.
```python
def split_secret_secure(threshold, total, secret, index_bits=8):
    if not isinstance(secret, bytes):
        raise TypeError("Secret as byte string required")
    if threshold > 255 or total > 255:
        raise ValueError("Threshold and total shares must be <= 255")
        
    index_max = 2 ** index_bits - 1
    if total > index_max:
        raise ValueError("Index bits value is too low")

    # Establish isolated, unique non-zero x-coordinates in GF(256)
    csprng = random.SystemRandom()
    shares_indexes = set()
    while len(shares_indexes) < total:
        x_val = csprng.randint(1, 255)
        shares_indexes.add(x_val)
    shares_indexes = list(shares_indexes)

    # Pre-allocate output buffers to optimize against timing analysis
    secret_len = len(secret)
    shares_buffers = {x: bytearray(secret_len) for x in shares_indexes}

    # Enforce strict loop-boundary isolation for each byte of the secret
    for byte_idx, b in enumerate(secret):
        # Explicitly sample independent coefficients for every individual byte
        q = [b] + [csprng.randint(0, 255) for _ in range(threshold - 1)]

        # Polynomial evaluation via Horner's Method
        for x in shares_indexes:
            r = 0
            for coefficient in reversed(q):
                r = _gf256_add(_gf256_mul(r, x), coefficient)
            
            # Constant-time buffer mutation
            shares_buffers[x][byte_idx] = r

    return {x: bytes(buf) for x, buf in shares_buffers.items()}

```
## 5. Conclusion
Fixing the non-uniform distribution of individual coefficients (as discussed in historic issues) is insufficient if the sequential allocation logic chains those coefficients across byte operations. Resolving this state-leakage vulnerability is critical to maintaining the mathematical integrity of user backups and private seed shares.
